#!/bin/sh

PROJECT_NAME=$(basename "$(pwd)")
echo "Project name detected: $PROJECT_NAME"

VERSION_HEADER="source/${PROJECT_NAME}/version.h"
mkdir -p "source/${PROJECT_NAME}"
MAJOR=0

# Проверка: в git-репозитории?
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo "Error: not in a git repository"
    exit 1
fi

# ----------------------------
# Автоопределение главной ветки: main или master
# ----------------------------
PRIMARY_BRANCH=""
if git show-ref --quiet refs/heads/main; then
    # Проверим, есть ли main и активен ли он в истории
    if git log -n 1 main --oneline > /dev/null 2>&1; then
        PRIMARY_BRANCH="main"
    fi
fi

if [ -z "$PRIMARY_BRANCH" ] && git show-ref --quiet refs/heads/master; then
    if git log -n 1 master --oneline > /dev/null 2>&1; then
        PRIMARY_BRANCH="master"
    fi
fi

if [ -z "$PRIMARY_BRANCH" ]; then
    echo "Error: neither 'main' nor 'master' branch exists"
    exit 1
fi

echo "Primary branch detected: $PRIMARY_BRANCH"

# ----------------------------
# MINOR: количество слияний develop → PRIMARY_BRANCH
# ----------------------------
MERGE_LOG=$(git log "$PRIMARY_BRANCH" --merges --oneline --first-parent 2>/dev/null)
MINOR=0
echo "$MERGE_LOG" | grep -i "develop" | while read line; do
    MINOR=$((MINOR + 1))
done

# ----------------------------
# PATCH: количество коммитов в ветке develop
# ----------------------------
if git show-ref --quiet refs/heads/develop; then
    PATCH=$(git rev-list develop --count 2>/dev/null)
else
    # Если develop нет — используем PRIMARY_BRANCH
    PATCH=$(git rev-list "$PRIMARY_BRANCH" --count 2>/dev/null)
fi

# ----------------------------
# Fallback
# ----------------------------
[ -z "$MINOR" ] && MINOR=0
[ -z "$PATCH" ] && PATCH=0

# ----------------------------
# Генерируем version.h
# ----------------------------
cat > "$VERSION_HEADER" << EOF
// AUTOGENERATED — DO NOT EDIT
// Generated by shell/update-version.sh
#pragma once

namespace ${PROJECT_NAME} {
constexpr auto PROJECT_NAME = "${PROJECT_NAME}";
constexpr auto PROJECT_VERSION_MAJOR = $MAJOR;
constexpr auto PROJECT_VERSION_MINOR = $MINOR;
constexpr auto PROJECT_VERSION_PATCH = $PATCH;
} // namespace ${PROJECT_NAME}
EOF

echo "Version updated: $MAJOR.$MINOR.$PATCH"
git add "$VERSION_HEADER"
