# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.6.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.6.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/volodja/workspace/qtcreator/utility

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/volodja/workspace/qtcreator/utility

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.6.1/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.6.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.6.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/volodja/workspace/qtcreator/utility/CMakeFiles /Users/volodja/workspace/qtcreator/utility/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/volodja/workspace/qtcreator/utility/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named utility-test

# Build rule for target.
utility-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utility-test
.PHONY : utility-test

# fast build rule for target.
utility-test/fast:
	$(MAKE) -f CMakeFiles/utility-test.dir/build.make CMakeFiles/utility-test.dir/build
.PHONY : utility-test/fast

#=============================================================================
# Target rules for targets named utility

# Build rule for target.
utility: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utility
.PHONY : utility

# fast build rule for target.
utility/fast:
	$(MAKE) -f CMakeFiles/utility.dir/build.make CMakeFiles/utility.dir/build
.PHONY : utility/fast

utility-test/source/main.o: utility-test/source/main.cpp.o

.PHONY : utility-test/source/main.o

# target to build an object file
utility-test/source/main.cpp.o:
	$(MAKE) -f CMakeFiles/utility-test.dir/build.make CMakeFiles/utility-test.dir/utility-test/source/main.cpp.o
.PHONY : utility-test/source/main.cpp.o

utility-test/source/main.i: utility-test/source/main.cpp.i

.PHONY : utility-test/source/main.i

# target to preprocess a source file
utility-test/source/main.cpp.i:
	$(MAKE) -f CMakeFiles/utility-test.dir/build.make CMakeFiles/utility-test.dir/utility-test/source/main.cpp.i
.PHONY : utility-test/source/main.cpp.i

utility-test/source/main.s: utility-test/source/main.cpp.s

.PHONY : utility-test/source/main.s

# target to generate assembly for a file
utility-test/source/main.cpp.s:
	$(MAKE) -f CMakeFiles/utility-test.dir/build.make CMakeFiles/utility-test.dir/utility-test/source/main.cpp.s
.PHONY : utility-test/source/main.cpp.s

utility-test/source/utility/networking/server/socket/socket-test.o: utility-test/source/utility/networking/server/socket/socket-test.cpp.o

.PHONY : utility-test/source/utility/networking/server/socket/socket-test.o

# target to build an object file
utility-test/source/utility/networking/server/socket/socket-test.cpp.o:
	$(MAKE) -f CMakeFiles/utility-test.dir/build.make CMakeFiles/utility-test.dir/utility-test/source/utility/networking/server/socket/socket-test.cpp.o
.PHONY : utility-test/source/utility/networking/server/socket/socket-test.cpp.o

utility-test/source/utility/networking/server/socket/socket-test.i: utility-test/source/utility/networking/server/socket/socket-test.cpp.i

.PHONY : utility-test/source/utility/networking/server/socket/socket-test.i

# target to preprocess a source file
utility-test/source/utility/networking/server/socket/socket-test.cpp.i:
	$(MAKE) -f CMakeFiles/utility-test.dir/build.make CMakeFiles/utility-test.dir/utility-test/source/utility/networking/server/socket/socket-test.cpp.i
.PHONY : utility-test/source/utility/networking/server/socket/socket-test.cpp.i

utility-test/source/utility/networking/server/socket/socket-test.s: utility-test/source/utility/networking/server/socket/socket-test.cpp.s

.PHONY : utility-test/source/utility/networking/server/socket/socket-test.s

# target to generate assembly for a file
utility-test/source/utility/networking/server/socket/socket-test.cpp.s:
	$(MAKE) -f CMakeFiles/utility-test.dir/build.make CMakeFiles/utility-test.dir/utility-test/source/utility/networking/server/socket/socket-test.cpp.s
.PHONY : utility-test/source/utility/networking/server/socket/socket-test.cpp.s

utility/source/utility/networking/server/socket/implementation/socket.o: utility/source/utility/networking/server/socket/implementation/socket.cpp.o

.PHONY : utility/source/utility/networking/server/socket/implementation/socket.o

# target to build an object file
utility/source/utility/networking/server/socket/implementation/socket.cpp.o:
	$(MAKE) -f CMakeFiles/utility-test.dir/build.make CMakeFiles/utility-test.dir/utility/source/utility/networking/server/socket/implementation/socket.cpp.o
	$(MAKE) -f CMakeFiles/utility.dir/build.make CMakeFiles/utility.dir/utility/source/utility/networking/server/socket/implementation/socket.cpp.o
.PHONY : utility/source/utility/networking/server/socket/implementation/socket.cpp.o

utility/source/utility/networking/server/socket/implementation/socket.i: utility/source/utility/networking/server/socket/implementation/socket.cpp.i

.PHONY : utility/source/utility/networking/server/socket/implementation/socket.i

# target to preprocess a source file
utility/source/utility/networking/server/socket/implementation/socket.cpp.i:
	$(MAKE) -f CMakeFiles/utility-test.dir/build.make CMakeFiles/utility-test.dir/utility/source/utility/networking/server/socket/implementation/socket.cpp.i
	$(MAKE) -f CMakeFiles/utility.dir/build.make CMakeFiles/utility.dir/utility/source/utility/networking/server/socket/implementation/socket.cpp.i
.PHONY : utility/source/utility/networking/server/socket/implementation/socket.cpp.i

utility/source/utility/networking/server/socket/implementation/socket.s: utility/source/utility/networking/server/socket/implementation/socket.cpp.s

.PHONY : utility/source/utility/networking/server/socket/implementation/socket.s

# target to generate assembly for a file
utility/source/utility/networking/server/socket/implementation/socket.cpp.s:
	$(MAKE) -f CMakeFiles/utility-test.dir/build.make CMakeFiles/utility-test.dir/utility/source/utility/networking/server/socket/implementation/socket.cpp.s
	$(MAKE) -f CMakeFiles/utility.dir/build.make CMakeFiles/utility.dir/utility/source/utility/networking/server/socket/implementation/socket.cpp.s
.PHONY : utility/source/utility/networking/server/socket/implementation/socket.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... utility-test"
	@echo "... utility"
	@echo "... utility-test/source/main.o"
	@echo "... utility-test/source/main.i"
	@echo "... utility-test/source/main.s"
	@echo "... utility-test/source/utility/networking/server/socket/socket-test.o"
	@echo "... utility-test/source/utility/networking/server/socket/socket-test.i"
	@echo "... utility-test/source/utility/networking/server/socket/socket-test.s"
	@echo "... utility/source/utility/networking/server/socket/implementation/socket.o"
	@echo "... utility/source/utility/networking/server/socket/implementation/socket.i"
	@echo "... utility/source/utility/networking/server/socket/implementation/socket.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

