// AUTOGENERATED — DO NOT EDIT
// Generated by shell/update-version.sh
#pragma once

namespace iridium.rubius {
constexpr auto PROJECT_NAME = "iridium.rubius";
constexpr auto PROJECT_VERSION_MAJOR = 0;
constexpr auto PROJECT_VERSION_MINOR = 0;
constexpr auto PROJECT_VERSION_PATCH = 400;
} // namespace iridium.rubius
