// AUTOGENERATED — DO NOT EDIT
// Generated by shell/update-version.sh
#pragma once

namespace iridium {
constexpr auto PROJECT_NAME = "iridium";
constexpr auto PROJECT_VERSION_MAJOR = 0;
constexpr auto PROJECT_VERSION_MINOR = 0;
constexpr auto PROJECT_VERSION_PATCH = 411;
} // namespace iridium
