// AUTOGENERATED — DO NOT EDIT
// Generated by shell/update-version.sh
#pragma once

namespace iridium {
/// \~english @brief The name of the project.
/// \~russian @brief Имя проекта.
constexpr auto PROJECT_NAME = "iridium";
/// \~english @brief The major version of the project.
/// \~russian @brief Основная версия проекта.
constexpr auto PROJECT_VERSION_MAJOR = 0;
/// \~english @brief The minor version of the project.
/// \~russian @brief Минорная версия проекта.
constexpr auto PROJECT_VERSION_MINOR = 0;
/// \~english @brief The patch version of the project.
/// \~russian @brief Патч-версия проекта.
constexpr auto PROJECT_VERSION_PATCH = 411;
} // namespace iridium
