// Copyright © 2019 Bulaev Vladimir.
// Contacts: <bulaev_vladimir@mail.ru>
// License: https://www.gnu.org/licenses/lgpl-3.0
//
// AUTOGENERATED — DO NOT EDIT
// Generated by shell/update-version.sh
#pragma once
#define IRIDIUM_VERSION_MAJOR 0
#define IRIDIUM_VERSION_MINOR 0
#define IRIDIUM_VERSION_PATCH 423
