#!/bin/sh

# -----------------------------------------------------------------------------
# Auto-detect project name from source/ directory structure
# -----------------------------------------------------------------------------
PROJECT_NAME=""
SOURCE_DIR="source/library"

if [ ! -d "$SOURCE_DIR" ]; then
    echo "Error: directory 'source/library' not found"
    exit 1
fi

for dir in "$SOURCE_DIR"/*/; do
    dir=${dir%/}
    dir_name=${dir##*/}

    case "$dir_name" in
        *-test|*-binary)
            continue
            ;;
        *)
            if [ -f "$dir/version.h" ]; then
                PROJECT_NAME="$dir_name"
                break
            fi
            ;;
    esac
done

if [ -z "$PROJECT_NAME" ]; then
    echo "Error: no main library folder found in 'source/'"
    echo "Expected: source/<name>/version.h (e.g. source/iridium/version.h)"
    exit 1
fi

echo "Project name auto-detected: $PROJECT_NAME"

# -----------------------------------------------------------------------------
# Verify we are in a git repository
# -----------------------------------------------------------------------------
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo "Error: not in a git repository"
    exit 1
fi

# -----------------------------------------------------------------------------
# Detect primary branch: main or master
# -----------------------------------------------------------------------------
PRIMARY_BRANCH=""
if git show-ref --quiet refs/heads/main > /dev/null 2>&1 && \
   git log -n 1 main --oneline > /dev/null 2>&1; then
    PRIMARY_BRANCH="main"
elif git show-ref --quiet refs/heads/master > /dev/null 2>&1 && \
     git log -n 1 master --oneline > /dev/null 2>&1; then
    PRIMARY_BRANCH="master"
else
    echo "Error: neither 'main' nor 'master' branch exists"
    exit 1
fi

echo "Primary branch detected: $PRIMARY_BRANCH"

# -----------------------------------------------------------------------------
# MINOR & PATCH: count merges from 'develop' and commits since last merge
# -----------------------------------------------------------------------------
MINOR=0
PATCH=0
DEVELOP_REF=""

# Prefer local 'develop'
if git show-ref --quiet refs/heads/develop 2>/dev/null; then
    DEVELOP_REF="develop"
else
    # Fallback: try remote
    if git show-ref --quiet refs/remotes/origin/develop 2>/dev/null; then
        DEVELOP_REF="origin/develop"
    fi
fi

if [ -z "$DEVELOP_REF" ]; then
    MINOR=0
    PATCH=$(git rev-list "$PRIMARY_BRANCH" --count 2>/dev/null || echo 0)
else
    MERGE_COMMITS=""
    for merge in $(git rev-list --merges --first-parent "$PRIMARY_BRANCH" 2>/dev/null); do
        if git log -1 --format='%s' "$merge" 2>/dev/null | grep -q "Merge branch 'develop'"; then
            if parent2=$(git rev-parse "$merge"^2 2>/dev/null) && \
               git merge-base --is-ancestor "$parent2" "$DEVELOP_REF" 2>/dev/null; then
                MERGE_COMMITS="$merge $MERGE_COMMITS"
            fi
        fi
    done

    if [ -n "$MERGE_COMMITS" ]; then
        MINOR=0
        LATEST_MERGE=""
        for m in $MERGE_COMMITS; do
            MINOR=$((MINOR + 1))
            [ -z "$LATEST_MERGE" ] && LATEST_MERGE="$m"
        done

        # ← ИСПРАВЛЕНИЕ: только коммиты develop, которых нет в master
        PATCH=$(git rev-list "$DEVELOP_REF" "^$PRIMARY_BRANCH" --count 2>/dev/null || echo 0)
    else
        MINOR=0
        PATCH=$(git rev-list "$DEVELOP_REF" "^$PRIMARY_BRANCH" --count 2>/dev/null || echo 0)
    fi
fi

# Fallbacks
[ -z "$MINOR" ] && MINOR=0
[ -z "$PATCH" ] && PATCH=0

# -----------------------------------------------------------------------------
# Write version.h
# -----------------------------------------------------------------------------
VERSION_HEADER="source/${PROJECT_NAME}/version.h"
mkdir -p "source/${PROJECT_NAME}"

UPPER_PROJECT_NAME=$(printf '%s' "$PROJECT_NAME" | tr '[:lower:]' '[:upper:]')

cat > "$VERSION_HEADER" << EOF
// Copyright © 2019 Bulaev Vladimir.
// Contacts: <bulaev_vladimir@mail.ru>
// License: https://www.gnu.org/licenses/lgpl-3.0
//
// AUTOGENERATED — DO NOT EDIT
// Generated by shell/update-version.sh
#pragma once
#define ${UPPER_PROJECT_NAME}_VERSION_MAJOR 0
#define ${UPPER_PROJECT_NAME}_VERSION_MINOR $MINOR
#define ${UPPER_PROJECT_NAME}_VERSION_PATCH $PATCH
EOF

echo "Version updated: 0.$MINOR.$PATCH"
git add "$VERSION_HEADER"
